server:
  port: 81
spring:
  profiles:
    active: druid

knife4j:
  enable: true
  setting:
    enableRequestCache: false

# 指定数据库语句编写的xml文件位置
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
